---
- name: download confd
  become: yes
  become_user: root
  get_url:
    url: '{{confd_url}}'
    dest: /usr/local/bin/{{confd_name}}
    mode: 0755

- name: link confd
  become: yes
  become_user: root
  file:
    src: /usr/local/bin/{{confd_name}}
    dest: /usr/local/bin/confd
    state: link
