---
- name: downloading {{ confd_url }} to {{ confd_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ confd_url }}'
    dest: '{{ confd_exe }}'
    checksum: '{{ confd_checksum }}'
    mode: 0755

- name: linking confd {{ confd_link }} to {{ confd_exe }}
  become: true
  become_user: root
  file:
    src: '{{ confd_exe }}'
    dest: '{{ confd_link }}'
    state: link
